namespace RagEval.Models;

/// <summary>
/// Represents a single question/answer/context triple produced by a RAG pipeline,
/// to be scored by <see cref="RagEvaluator"/>.
/// </summary>
public sealed class RagEvaluationInput
{
    /// <summary>The question that was posed to the RAG pipeline.</summary>
    public required string Question { get; init; }

    /// <summary>The answer generated by the RAG pipeline.</summary>
    public required string Answer { get; init; }

    /// <summary>The context chunks retrieved by the RAG pipeline and used to generate the answer.</summary>
    public required IReadOnlyList<string> Contexts { get; init; }

    /// <summary>
    /// An optional reference answer used to compute <see cref="Models.RagEvaluationResult.ContextRecall"/>.
    /// When omitted, context recall is not evaluated.
    /// </summary>
    public string? GroundTruth { get; init; }
}
